### ISSUE TITLE
Issue with Android upload

### ISSUE THREAD

**Issue by irademos** [storj/uplink-android#10]
So I'm not sure what I'm doing wrong here. I'm able to list objects and download objects without a problem. But when I try to upload a .jpg or .png image to 'my-bucket,' the file doesn't seem to upload. I see the bytes being uploaded and I'm not catching any errors. But afterwards, I don't see any new files in 'my-bucket.'

I've tried a .jpg of 80kb and a .png of 800kb. I've tried different buffer sizes as well, between 8kb and 128kb

Here is the code:

```
try (Project project = uplink.openProject(access);
                 OutputStream out = project.uploadObject(bucket, objectKey);
                 InputStream in = new FileInputStream(photoDir)) {
             byte[] buffer = new byte[size * 1024];
             int bytesRead;
             while ((bytesRead = in.read(buffer)) != -1) {
                 out.write(buffer, 0, bytesRead);
             }
         } catch(Exception e) {
            Log.v(e.getMessage());
         }
```

Any help appreciated!

**Comment by mniewrzal** [comment]
Hi @irademos 
Thanks for trying our library for Android! Can you give me an exact version of library you are using?

**Comment by irademos** [comment]
Hi @mniewrzal, I am using 'io.storj:uplink-android:1.0.0-rc.1' in the build.gradle, as instructed in Setup.

**Comment by mniewrzal** [comment]
It looks that your code is missing `commit()` method. You need to change `OutputStream` into `ObjectOutputStream` and after writing all data just execute `out.commit();`. See code below: 
```
try (Project project = uplink.openProject(access);
                 ObjectOutputStream out = project.uploadObject(bucket, objectKey);
                 InputStream in = new FileInputStream(photoDir)) {
         byte[] buffer = new byte[size * 1024];
         int bytesRead;
         while ((bytesRead = in.read(buffer)) != -1) {
             out.write(buffer, 0, bytesRead);
         }
         out.commit();
 } catch(Exception e) {
    Log.v(e.getMessage());
 }
```
It looks that the main README is outdated in a few places. Sorry about that!

**Comment by irademos** [comment]
Great, that fixed it. Thanks!
