### ISSUE TITLE
Upload successful, but no files

### ISSUE THREAD

**Issue by q601180252** [storj/uplink-android#13]
access = uplink2.requestAccessWithPassphrase(satelliteAddress, serializedApiKey, passphrase);
        try (Project project = uplink2.openProject(access);
             OutputStream out = project.uploadObject("my-bucket", "test.jpg");
             InputStream in = new FileInputStream(file)) {
            byte[] buffer = new byte[1024];
            int bytesRead;
            while ((bytesRead = in.read(buffer)) != -1) {
                out.write(buffer, 0, bytesRead);
            }
            out.flush();
//            out.close();
        }

**Comment by Erikvv** [comment]
You should call .commit()

```
ObjectOutputStream out = project.uploadObject("my-bucket", "test.jpg");

/* write */

out.commit();
```
