### ISSUE TITLE
Opening a project fails

### ISSUE THREAD

**Issue by dri94** [storj/uplink-android#2]
When opening a project as specified in instructions, the following error is returned 
```
go.Universe$proxyerror: metainfo error: rpccompat: dial tcp: lookup us-central-1.tardigrade.io: No address associated with hostname
```

The satellite address I am using is `us-central-1.tardigrade.io:7777`

My code is
```
    fun login(
        satelliteAddress: String,
        apiKey: String,
        encryptionAccess: String
    ): Result<Scope, Exception> {
        val key = ApiKey.parse(apiKey)
        return try {
            val project = Uplink().openProject(satelliteAddress, key)
            val saltedKey = Key.getSaltedKeyFromPassphrase(project, encryptionAccess)
            val access = EncryptionAccess(saltedKey)
            Success(Scope(satelliteAddress, key, access))
        } catch (ex: StorjException) {
            return Error(ex)
        }
    }
```

**Comment by kaloyan-raev** [comment]
This error means that the `us-central-1.tardigrade.io` DNS name cannot be resolved on your device/emulator.

Make sure that your device/emulator is connected to Internet and that your app has the `android.permission.INTERNET` in the manifest.

**Comment by dri94** [comment]
I feel really embarrassed by that mistake lol. However is there any way to get more human readable error messages? This will make it easier for devs to understand, and bubble up the info to users

**Comment by kaloyan-raev** [comment]
Ideally, this should be an `UnknownHostException`, but we are not there yet in converting Golang errors to Java exceptions. We plan to have this in the future.

**Comment by dri94** [comment]
I still currently get an `io.storj.StorjException: go.Universe$proxyerror: metainfo error: rpccompat: dial tcp 35.184.17.243:7777: socket: operation not permitted` when trying to perform this code
