### ISSUE TITLE
Error when list objects

### ISSUE THREAD

**Issue by zapburp** [storj/uplink-android#9]
When I try to get objects that were loaded from desktop uplink I get the error:
`go.Universe$Proxyerror: segment size must be larger than 0`

I've tried both source code from the master and uplink-1.0 branches.

**Comment by mniewrzal** [comment]
Are you able to share your code? Also, can you try version `1.0.0-rc.1`?

https://mvnrepository.com/artifact/io.storj/uplink-android/1.0.0-rc.1

**Comment by zapburp** [comment]
@mniewrzal I'm sorry the issue is related to the demo version of uplink client on android - hello storj.

But I also have trouble related to this repository...
So, when I try to open project
```
Access access = Access.parse(MY_ACCESS_STRING);
Uplink uplink = new Uplink();
uplink.openProject(access);
```
I get the error:
```
uplink: metainfo error: rpccompat: dial tcp: lookup asia-east-1.tardigrade.io: No address associated with hostname
	storj.io/common/rpc.Dialer.dialTransport:211
	storj.io/common/rpc.Dialer.dial:188
	storj.io/common/rpc.Dialer.DialNodeURL:148
	storj.io/uplink/private/metainfo.DialNodeURL:68
	storj.io/uplink.Config.dial:81
	storj.io/uplink.Config.OpenProject:68
	main.open_project:39
	main._cgoexpwrap_24a684d6393f_open_project:939
	runtime.cgocallbackg1:332
	runtime.cgocallbackg:207
	runtime.cgocallback_gofunc:806
```
First I thought that something is wrong with the parse access function but when I saw that the satellite is correct I rejected this version.

In my gradle script I have the line `implementation 'io.storj:uplink-android:1.0.0-rc.1'`

**Comment by mniewrzal** [comment]
Did you make your project from scratch? It looks like a connectivity issue. Did you set additional permissions in project manifest? Should be something like:
```
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```
